package think.repr;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.function.Function;
import java.util.function.Predicate;
import think.tools.Iteration;

/**
    Simplified Pathery problem parser. Structurally, the unification of problem
    metadata and its initial grid.
 */
public final class Problem {

    public static final class BadMapCodeException extends Exception {}

    public enum Feature {
        EMPTY,
        CHECKPOINT,
        SYSTEM_WALL,
        PLAYER_WALL,
        TELEPORT_IN,
        TELEPORT_OUT,
    }

    private static final String LOWERCASE_LETTER_REGEX = "[a-z]";
    private static final String PERIOD_REGEX = "\\.";
    private static final String COLON_REGEX = ":";
    private static final String PERIOD_OR_COMMA_REGEX = "[.,]";
    private static final String DIGITS_REGEX = "\\d+";

    private static final int NUM_METADATA_PARTS = 7;
    private static final int NUM_CHECKPOINTS = 14;
    private static final int NUM_TELEPORTS = 7;
    private static final int MAX_NAME_LENGTH = 100;

    private static final String START_SYMBOL = "s";
    private static final String FINISH_SYMBOL = "f";
    private static final String WALL_SYMBOL = "r";
    private static final String CHECKPOINT_SYMBOL = "c";
    private static final String TELEPORT_IN_SYMBOL = "t";
    private static final String TELEPORT_OUT_SYMBOL = "u";

    private final int numRows;
    private final int numCols;
    private final int playerWallSupply;
    private final Grid<Feature> initial;
    private final ArrayList<Cell> checkpoints;
    private final HashMap<Cell, Cell> teleports;
    private final String name;

    // == Parser (constructor). ========================================================

    /**
        Parse a problem generated by {@see https://www.pathery.com/mapeditor the
        pathery map editor}. Only start, finish, checkpoints, system walls, and
        teleports are supported. Start, finish, and checkpoints, and teleports must be
        unique. Player wall supply must be at least 1.

        @param
            mapCode a Pathery MapCode, which serves as the problem specification
        @throws
            BadMapCodeException if mapCode is malformed or contains unsupported features
     */
    /*
         A MapCode consists of a metadata section and grid section. These are separated
         by a colon.

         The metadata section is a series of exactly seven subsections separated by
         periods. The first three are width (colBound), height (rowBound), and the
         player's wall supply (playerWallSupply). The fourth is the map name. I don't
         know what the other sections do.

         The grid section consists of a series of features or skips. These are
         separated by inanely distributed commas or periods. A skip is an arbritrary
         strictly positive integer representing a run of empty cells in the
         one-dimensional representation of a grid. A feature is a string that maps to a
         special type of cell.

         Supported features:
           - s1: Green start
           - f1: Finish
           - r1 and r3: System wall
           - c1 to c14: Checkpoints 1 to 14
           - t1 to t7: Teleport ins 1 to 7
           - u1 to u7: Teleport outs 1 to 7

        Unsupported features:
          - s2: Red start
          - p1: Unbuildable
          - x1: Green single path
          - x2: Red single path
          - z5: Ice
          - r2: Player wall (since these are from solutions, rather than problems).

        The above list is complete as of January 2026. All supported features except
        for system walls must be unique or absent. Teleport ins must be paired with
        teleport outs. All supported features must live in the grid.
     */
    @SuppressWarnings(
        { "checkstyle:CyclomaticComplexity", "checkstyle:ExecutableStatementCount" }
    )
    public Problem(final String mapCode) throws BadMapCodeException {
        // == Section parsing. ==
        final String[] parts = mapCode.split(COLON_REGEX);
        require(parts.length == 2);

        // == Metadata parsing. ==
        final String[] metadata = parts[0].split(PERIOD_REGEX, -1);
        require(metadata.length == NUM_METADATA_PARTS);
        this.numCols = strToInt(metadata[0]);
        this.numRows = strToInt(metadata[1]);
        final int proposedPlayerWallSupply = strToInt(metadata[2]);
        this.name = cleanName(metadata[3]);

        final Function<Integer, Cell> indexToCell = index -> {
            return new Cell(index / numCols, index % numCols);
        };

        // == Grid parsing: temporary data holders. ==
        final String[] features = parts[1].split(PERIOD_OR_COMMA_REGEX);
        final ArrayList<Feature> cells = Iteration.filledArray(
            Feature.EMPTY,
            numRows * numCols
        );
        // checks is 1-indexed, while telIns/Outs is 0-indexed.
        final ArrayList<Cell> checks = Iteration.filledArray(
            Cell.OUT_OF_BOUNDS,
            NUM_CHECKPOINTS + 2 // get(0): start; get(size() - 1): end.
        );
        final ArrayList<Cell> telIns = Iteration.filledArray(
            Cell.OUT_OF_BOUNDS,
            NUM_TELEPORTS
        );
        final ArrayList<Cell> telOuts = Iteration.filledArray(
            Cell.OUT_OF_BOUNDS,
            NUM_TELEPORTS
        );
        int traversingIndex = 0;

        // == Grid parsing: feature traversal and syntax validation. ==
        for (final String feature : features) {
            if (feature.isBlank()) {
                continue;
            }
            require(traversingIndex < numRows * numCols);
            if (feature.matches(DIGITS_REGEX)) {
                traversingIndex += strToInt(feature);
                continue;
            }
            require(feature.length() >= 2);
            final String category = feature.substring(0, 1);
            require(category.matches(LOWERCASE_LETTER_REGEX));
            final int annotation = strToInt(feature.substring(1));
            require(feature.substring(1).matches(DIGITS_REGEX));
            switch (category) {
                case START_SYMBOL -> {
                    require(annotation == 1);
                    require(checks.get(0) == Cell.OUT_OF_BOUNDS);
                    checks.set(0, indexToCell.apply(traversingIndex));
                    cells.set(traversingIndex, Feature.CHECKPOINT);
                }
                case FINISH_SYMBOL -> {
                    require(annotation == 1);
                    require(checks.get(NUM_CHECKPOINTS + 1).equals(Cell.OUT_OF_BOUNDS));
                    checks.set(NUM_CHECKPOINTS + 1, indexToCell.apply(traversingIndex));
                    cells.set(traversingIndex, Feature.CHECKPOINT);
                }
                case WALL_SYMBOL -> {
                    final int wallType1 = 1;
                    final int wallType3 = 3;
                    require(annotation == wallType1 || annotation == wallType3);
                    cells.set(traversingIndex, Feature.SYSTEM_WALL);
                }
                case CHECKPOINT_SYMBOL -> {
                    require(annotation >= 1 && annotation <= NUM_CHECKPOINTS);
                    require(checks.get(annotation).equals(Cell.OUT_OF_BOUNDS));
                    checks.set(annotation, indexToCell.apply(traversingIndex));
                    cells.set(traversingIndex, Feature.CHECKPOINT);
                }
                case TELEPORT_IN_SYMBOL -> {
                    require(annotation >= 1 && annotation <= NUM_TELEPORTS);
                    require(telIns.get(annotation - 1).equals(Cell.OUT_OF_BOUNDS));
                    telIns.set(annotation - 1, indexToCell.apply(traversingIndex));
                    cells.set(traversingIndex, Feature.TELEPORT_IN);
                }
                case TELEPORT_OUT_SYMBOL -> {
                    require(annotation >= 1 && annotation <= NUM_TELEPORTS);
                    require(telOuts.get(annotation - 1).equals(Cell.OUT_OF_BOUNDS));
                    telOuts.set(annotation - 1, indexToCell.apply(traversingIndex));
                    cells.set(traversingIndex, Feature.TELEPORT_OUT);
                }
                default -> {
                    require(false);
                }
            }
            traversingIndex += 1;
        }
        require(traversingIndex <= numRows * numCols);

        // == Grid parsing: semantic validation. ==
        final boolean pairedTels = Iteration.zip(telIns, telOuts).allMatch(
            pair ->
                (pair.first().equals(Cell.OUT_OF_BOUNDS)) ==
                (pair.second().equals(Cell.OUT_OF_BOUNDS))
        );
        final boolean hasStart = !checks.get(0).equals(Cell.OUT_OF_BOUNDS);
        final boolean hasEnd = !checks
            .get(NUM_CHECKPOINTS + 1)
            .equals(Cell.OUT_OF_BOUNDS);
        require(pairedTels && hasStart && hasEnd);

        // == Grid parsing: building. ==
        this.initial = new Grid<>(cells, numRows, numCols);
        this.checkpoints = new ArrayList<>();
        checks
            .stream()
            .filter(cell -> !cell.equals(Cell.OUT_OF_BOUNDS))
            .forEachOrdered(checkpoints::add);
        this.teleports = new HashMap<>();
        Iteration.zip(telIns, telOuts)
            .filter(pair -> !pair.first().equals(Cell.OUT_OF_BOUNDS))
            .forEachOrdered(pair -> {
                teleports.put(pair.first(), pair.second());
            });

        // Pathery often supplies more walls than possible to place. I don't want to
        // prohibit that in MapCodes, but I don't want to let it through either.
        this.playerWallSupply = Math.min(
            proposedPlayerWallSupply,
            (int) initial.where(Feature.EMPTY::equals).count()
        );
    }

    private static void require(final Boolean condition) throws BadMapCodeException {
        // The parser should throw our custom exception instead of unexpectedly
        // failing. But we don't want wrap everything in a massive try-except because
        // that sort of lazy programming silently surpresses bugs.
        if (!condition) {
            throw new BadMapCodeException();
        }
    }

    private static int strToInt(final String number) throws BadMapCodeException {
        try {
            // All MapCode numbers are strictly positive plain integers.
            require(number.matches(DIGITS_REGEX));
            final int result = Integer.parseInt(number);
            require(result >= 1);
            return result;
        } catch (NumberFormatException exception) {
            throw new BadMapCodeException();
        }
    }

    private static String cleanName(final String raw) throws BadMapCodeException {
        final String stripped = raw.strip();
        require(stripped.chars().noneMatch(chr -> (chr == '\n' || chr == '\r')));
        return stripped.substring(0, Math.min(stripped.length(), MAX_NAME_LENGTH));
    }

    // == Public API. ==================================================================

    public String getName() {
        return name;
    }

    /**
        Returns the initial grid of the problem.

        The initial grid is read-only; modifying it is a design error. Use {@link
        #getAnotherInitial()} if modification is desired.
     */
    public Grid<Feature> getCachedInitial() {
        // SpotBugs will correctly tell you this exposes mutable internal state. This
        // method exists anyway because it is more performant and callers are expected
        // to be well-behaved.
        return initial;
    }

    public Grid<Feature> getAnotherInitial() {
        return new Grid<>(initial);
    }

    public int getPlayerWallSupply() {
        return playerWallSupply;
    }

    public ArrayList<Cell> getCheckpoints() {
        return new ArrayList<>(checkpoints);
    }

    public HashMap<Cell, Cell> getTeleports() {
        return new HashMap<>(teleports);
    }

    public boolean isValid(final Grid<Feature> solution) {
        final Predicate<Cell> legalMove = cell -> {
            final boolean unchanged = initial.get(cell) == solution.get(cell);
            final boolean assigned =
                initial.get(cell) == Feature.EMPTY &&
                solution.get(cell) == Feature.PLAYER_WALL;
            return unchanged || assigned;
        };
        final boolean enoughSupply =
            solution.where(Feature.PLAYER_WALL::equals).count() <= playerWallSupply;
        final boolean sameSize =
            initial.getNumRows() == solution.getNumRows() &&
            initial.getNumCols() == solution.getNumCols();
        return (
            sameSize &&
            enoughSupply &&
            initial.stream().allMatch(pair -> legalMove.test(pair.second()))
        );
    }
}
