"""Generate a random Pathery problem that satisfies the parser.

A `.tpai` file consists of a metadata and grid section separated by `;;;`. The metadata
is a non-negative integer player wall count. The grid is a list of rows separated by
`;;`. A row is a list of cells seperated by `;`. There must be at least one cell and all
rows must have an equal number of cells. Each cell is `#` (system wall), `.` (empty),
or a unique integer (checkpoint). Whitespace is ignored.

Here's an example where the snake tries to get from the top left to top right of a 3 by
3 grid, there's a system wall in the middle, and the player can place 3 player walls:

```
3;;;
0;.;1;;
.;#;.
.;.;.
```

The problem generated by this file is solveable if the player is allowed to not place
any player walls. If the player is forced to place player walls, the problem may not be
solveable.
"""

from __future__ import annotations

import argparse
import random
import sys
from collections import deque
from itertools import pairwise

# ruff: noqa: T201 INP001 S311

__all__: list[str] = []

Cell = str
Grid = list[list[Cell]]
Position = tuple[int, int]

EMPTY: Cell = "."
SYSTEM_WALL: Cell = "#"


class CantGenerateError(Exception): ...


def is_connected(grid: Grid, start: Position, goal: Position) -> bool:  # Standard BFS.
    height = len(grid)
    width = len(grid[0])
    queue: deque[Position] = deque([start])
    visited: set[Position] = {start}
    while queue:
        row, col = queue.popleft()
        if (row, col) == goal:
            return True
        for drow, dcol in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            nrow = row + drow
            ncol = col + dcol
            if (
                0 <= nrow < height
                and 0 <= ncol < width
                and grid[nrow][ncol] != SYSTEM_WALL
                and (nrow, ncol) not in visited
            ):
                visited.add((nrow, ncol))
                queue.append((nrow, ncol))
    return False


def all_connected(grid: Grid, checkpoints: list[Position]) -> bool:
    return all(is_connected(grid, start, end) for start, end in pairwise(checkpoints))


def generate_problem(
    height: int,
    width: int,
    system_wall_probability: float,
    checkpoint_count: int,
    max_attempts: int,
) -> Grid:
    def pick_cell(row: int, col: int) -> str:
        return str(checkpoint_map.get((row, col), "")) or (
            SYSTEM_WALL if random.random() < system_wall_probability else EMPTY
        )

    if any(value <= 0 for value in (height, width, max_attempts)):
        raise ValueError
    if checkpoint_count not in range(2, height * width):
        raise ValueError
    for _ in range(max_attempts):
        checkpoints = random.sample(range(height * width), checkpoint_count)
        checkpoints = [
            (position // width, position % width) for position in checkpoints
        ]
        checkpoint_map = {position: index for index, position in enumerate(checkpoints)}
        grid = [[pick_cell(row, col) for col in range(width)] for row in range(height)]
        if all_connected(grid, checkpoints):
            return grid
    raise CantGenerateError


def format_problem(
    grid: Grid,
    player_wall_count: int,
) -> str:
    section_delim = ";;;"
    line_delim = ";;"
    cell_delim = ";"
    return section_delim.join(
        (
            str(player_wall_count),
            line_delim.join(cell_delim.join(line) for line in grid),
        ),
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    _ = parser.add_argument("--height", type=int, default=7)
    _ = parser.add_argument("--width", type=int, default=13)
    _ = parser.add_argument("--system-wall-probability", type=float, default=0.1)
    _ = parser.add_argument("--checkpoints", type=int, default=3)
    _ = parser.add_argument("--player-walls", type=int, default=7)
    _ = parser.add_argument("--max-attempts", type=int, default=100)
    args = parser.parse_args()

    try:
        grid = generate_problem(
            height=args.height,  # pyright: ignore[reportAny]
            width=args.width,  # pyright: ignore[reportAny]
            system_wall_probability=args.system_wall_probability,  # pyright: ignore[reportAny]
            checkpoint_count=args.checkpoints,  # pyright: ignore[reportAny]
            max_attempts=args.max_attempts,  # pyright: ignore[reportAny]
        )
    except CantGenerateError:
        print("Failed to generate problem.", file=sys.stderr)
        return 1
    except ValueError:
        print("Invalid input.", file=sys.stderr)
        return 1
    print(
        format_problem(grid, args.player_walls),  # pyright: ignore[reportAny]
        file=sys.stdout,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
