package infra.io;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.TreeMap;
import java.util.function.Function;
import think.repr.Cell;
import think.repr.Grid;
import think.repr.Problem;
import think.repr.Problem.Feature;
import think.tools.Iteration;

/**
    Parse a Problem in the form of a MapCode generated by {@see
    https://www.pathery.com/mapeditor the Pathery map editor}. Only start, finish,
    checkpoints, system walls, and teleports are supported. Start, finish, and
    checkpoints, and teleports must be unique. See docs/problem_statement.md for more
    context.
 */
/*
    A MapCode consists of a metadata section and grid section. These are separated by a
    colon.

    The metadata section is a series of exactly seven subsections separated by periods.
    The first four are width (numCols), height (numRows), the player's wall supply
    (playerWallSupply), and map name. I don't know what the other sections do.

    The grid section consists of a series of features or skips. These are separated by
    inanely distributed commas or periods. A skip is an arbritrary strictly positive
    integer representing a run of empty cells in the one-dimensional representation of
    a grid.

    A feature is a string that maps to a special type of cell. Pathery believes
    features are a letter followed by a limited set of numbers, but we generalize that
    to any strictly positive number. In the following, "N" means "a strictly positive
    integer".

    Supported features:
      - s1: Green start
      - f1: Finish
      - r1, r3: System wall
      - cN: Checkpoint
      - tN: Teleport-in
      - uN: Teleport-out

    Unsupported features:
      - s2: Red start
      - p1: Unbuildable
      - x1: Green single path
      - x2: Red single path
      - z5: Ice
      - r2: Player wall (since these are from solutions, rather than problems).

      The above list is complete as of January 2026. All supported features except for
      system walls must be unique or absent. Teleport ins must be paired with teleport
      outs. All supported features must live in the grid.
 */
public final class MapCodeParser {

    public static final class BadMapCodeException extends Exception {}

    private static final String LOWERCASE_LETTER_REGEX = "[a-z]";
    private static final String PERIOD_REGEX = "\\.";
    private static final String COLON_REGEX = ":";
    private static final String PERIOD_OR_COMMA_REGEX = "[.,]";
    private static final String DIGITS_REGEX = "\\d+";

    private static final int NUM_METADATA_PARTS = 7;
    private static final int MAX_NAME_LENGTH = 100;

    private static final String START_SYMBOL = "s";
    private static final String FINISH_SYMBOL = "f";
    private static final String WALL_SYMBOL = "r";
    private static final String CHECKPOINT_SYMBOL = "c";
    private static final String TELEPORT_IN_SYMBOL = "t";
    private static final String TELEPORT_OUT_SYMBOL = "u";

    private final String mapCode;

    public MapCodeParser(final String mapCode) {
        this.mapCode = mapCode;
    }

    public Problem parse() throws BadMapCodeException {
        final String[] parts = mapCode.split(COLON_REGEX, -1);
        require(parts.length == 2);
        final MetaData metaData = parseMetaData(parts[0]);
        final RawGridData rawGridData = parseRawGridData(metaData, parts[1]);
        final AssembledGridData assembledGridData = assembleGridData(
            metaData,
            rawGridData
        );
        return new Problem(
            metaData.name,
            assembledGridData.clampedPlayerWallSupply,
            assembledGridData.grid,
            assembledGridData.checkpoints,
            assembledGridData.teleports
        );
    }

    // == Sections. ====================================================================

    private static MetaData parseMetaData(final String metaData)
        throws BadMapCodeException {
        final String[] parts = metaData.split(PERIOD_REGEX, -1);
        require(parts.length == NUM_METADATA_PARTS);
        final int numCols = toPositive(parts[0]);
        final int numRows = toPositive(parts[1]);
        final int proposedWalls = toNonNegative(parts[2]);
        final String name = cleanName(parts[3]);
        return new MetaData(name, numCols, numRows, proposedWalls);
    }

    @SuppressWarnings(
        { "checkstyle:CyclomaticComplexity", "checkstyle:ExecutableStatementCount" }
    )
    private static RawGridData parseRawGridData(
        final MetaData metaData,
        final String rawGridData
    ) throws BadMapCodeException {
        final ArrayList<Feature> grid = Iteration.filledArray(
            Feature.EMPTY,
            metaData.numRows * metaData.numCols
        );
        final TreeMap<Integer, Cell> checksById = new TreeMap<>();
        final TreeMap<Integer, Cell> telInsById = new TreeMap<>();
        final TreeMap<Integer, Cell> telOutsById = new TreeMap<>();
        Cell start = Cell.OUT_OF_BOUNDS;
        Cell finish = Cell.OUT_OF_BOUNDS;

        final Function<Integer, Cell> indexToCell = index -> {
            return new Cell(index / metaData.numCols, index % metaData.numCols);
        };
        int traversingIndex = 0;
        for (String feature : rawGridData.split(PERIOD_OR_COMMA_REGEX)) {
            if (feature.isBlank()) {
                continue;
            }
            require(traversingIndex < metaData.numRows * metaData.numCols);
            if (feature.matches(DIGITS_REGEX)) {
                traversingIndex += toPositive(feature);
                continue;
            }
            require(feature.length() >= 2);
            final String category = feature.substring(0, 1);
            require(category.matches(LOWERCASE_LETTER_REGEX));
            final int annotation = toPositive(feature.substring(1));
            switch (category) {
                case START_SYMBOL -> {
                    require(annotation == 1);
                    require(start.equals(Cell.OUT_OF_BOUNDS));
                    start = indexToCell.apply(traversingIndex);
                    grid.set(traversingIndex, Feature.CHECKPOINT);
                }
                case FINISH_SYMBOL -> {
                    require(annotation == 1);
                    require(finish.equals(Cell.OUT_OF_BOUNDS));
                    finish = indexToCell.apply(traversingIndex);
                    grid.set(traversingIndex, Feature.CHECKPOINT);
                }
                case WALL_SYMBOL -> {
                    require(annotation == 1 || annotation == 3);
                    grid.set(traversingIndex, Feature.SYSTEM_WALL);
                }
                case CHECKPOINT_SYMBOL -> {
                    require(!checksById.containsKey(annotation));
                    checksById.put(annotation, indexToCell.apply(traversingIndex));
                    grid.set(traversingIndex, Feature.CHECKPOINT);
                }
                case TELEPORT_IN_SYMBOL -> {
                    require(!telInsById.containsKey(annotation));
                    telInsById.put(annotation, indexToCell.apply(traversingIndex));
                    grid.set(traversingIndex, Feature.TELEPORT_IN);
                }
                case TELEPORT_OUT_SYMBOL -> {
                    require(!telOutsById.containsKey(annotation));
                    telOutsById.put(annotation, indexToCell.apply(traversingIndex));
                    grid.set(traversingIndex, Feature.TELEPORT_OUT);
                }
                default -> {
                    require(false);
                }
            }
            traversingIndex += 1;
        }
        require(traversingIndex <= metaData.numRows * metaData.numCols);
        return new RawGridData(grid, start, finish, checksById, telInsById, telOutsById);
    }

    private static AssembledGridData assembleGridData(
        final MetaData metaData,
        final RawGridData rawGridData
    ) throws BadMapCodeException {
        final TreeMap<Integer, Cell> telInsById = rawGridData.telInsById;
        final TreeMap<Integer, Cell> telOutsById = rawGridData.telOutsById;
        require(!rawGridData.start.equals(Cell.OUT_OF_BOUNDS));
        require(!rawGridData.finish.equals(Cell.OUT_OF_BOUNDS));
        require(telInsById.keySet().equals(telOutsById.keySet()));

        final ArrayList<Cell> checkpoints = new ArrayList<>();
        checkpoints.add(rawGridData.start);
        // This operation inserts checkpoints in order as long as checksById is a
        // SortedMap (it happens to be a TreeMap).
        checkpoints.addAll(rawGridData.checksById.values());
        checkpoints.add(rawGridData.finish);
        final HashMap<Cell, Cell> teleports = new HashMap<>();
        telInsById
            .keySet()
            .forEach(key -> {
                teleports.put(telInsById.get(key), telOutsById.get(key));
            });
        // Pathery often supplies more walls than possible to place. We don't want to
        // prohibit that in input, but we don't want to let it through either.
        final int clampedPlayerWallSupply = Math.min(
            metaData.proposedPlayerWallSupply,
            (int) rawGridData.grid.stream().filter(Feature.EMPTY::equals).count()
        );
        final Grid<Feature> grid = new Grid<>(
            rawGridData.grid,
            metaData.numRows,
            metaData.numCols
        );
        return new AssembledGridData(
            grid,
            checkpoints,
            teleports,
            clampedPlayerWallSupply
        );
    }

    // == Helpers. =====================================================================

    private static void require(final boolean condition) throws BadMapCodeException {
        // The parser should throw our custom exception instead of unexpectedly
        // failing. But we don't want catch miscellaneous exceptions since that sort of
        // lazy programming silently surpresses bugs; only exceptions that we expect to
        // see should be caught.
        if (!condition) {
            throw new BadMapCodeException();
        }
    }

    private static int toPositive(final String number) throws BadMapCodeException {
        try {
            require(number.matches(DIGITS_REGEX));
            final int result = Integer.parseInt(number);
            require(result >= 1);
            return result;
        } catch (NumberFormatException exception) {
            throw new BadMapCodeException();
        }
    }

    private static int toNonNegative(final String number) throws BadMapCodeException {
        try {
            require(number.matches(DIGITS_REGEX));
            final int result = Integer.parseInt(number);
            require(result >= 0);
            return result;
        } catch (NumberFormatException exception) {
            throw new BadMapCodeException();
        }
    }

    private static String cleanName(final String raw) throws BadMapCodeException {
        final String stripped = raw.strip();
        require(stripped.chars().noneMatch(chr -> (chr == '\n' || chr == '\r')));
        return stripped.substring(0, Math.min(stripped.length(), MAX_NAME_LENGTH));
    }

    // == Records. =====================================================================

    private record MetaData(
        String name,
        int numCols,
        int numRows,
        int proposedPlayerWallSupply
    ) {}

    private record RawGridData(
        ArrayList<Feature> grid,
        Cell start,
        Cell finish,
        TreeMap<Integer, Cell> checksById,
        TreeMap<Integer, Cell> telInsById,
        TreeMap<Integer, Cell> telOutsById
    ) {}

    private record AssembledGridData(
        Grid<Feature> grid,
        ArrayList<Cell> checkpoints,
        HashMap<Cell, Cell> teleports,
        int clampedPlayerWallSupply
    ) {}
}
