package think.ana;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.function.BiFunction;
import java.util.function.Predicate;
import think.repr.Cell;
import think.repr.Grid;
import think.repr.Problem.Feature;
import think.tools.Structures.Pair;

/**
    Distance evaluation.
 */
public final class Distances {

    private Distances() {}

    /**
        Get the distance from the source cell to every other cell in the grid.

        In the resulting grid, negative numbers mean a cell is unreachable. Cells that
        are not open are always unreachable.
     */
    public static Grid<Integer> distanceFrom(
        final Grid<Feature> solution,
        final Cell source
    ) {
        // The "cells with a negative distance are unreachable" convention was chosen
        // because it is invariant under addition of distance grids with connected
        // sources. If the sources are not connected, it may not hold.

        // PERF: Unbox primitives, use raw indexes instead of Cells, inline and unroll
        // neighbor loop, reuse structures where possible.

        assert Snake.isOpen(solution.get(source)) && solution.inBounds(source);
        final int numRows = solution.getNumRows();
        final int numCols = solution.getNumCols();
        final Grid<Integer> distances = new Grid<>(-1, numRows, numCols);
        final ArrayDeque<Cell> frontier = new ArrayDeque<>();

        frontier.add(source);
        distances.set(source, 0);
        while (!frontier.isEmpty()) {
            final Cell current = frontier.removeFirst();
            for (final Cell neighbor : current.getNeighbors(solution)) {
                if (
                    Snake.isOpen(solution.get(neighbor)) && distances.get(neighbor) <= -1
                ) {
                    distances.set(neighbor, distances.get(current) + 1);
                    frontier.add(neighbor);
                }
            }
        }
        assert isConsistent(distances);
        return distances;
    }

    /**
        Get the path the snake would take from Start to End.

        The End must also be the source (distance == 0) of the distances grid
        generated by {@link #distanceFrom(Grid, Cell)}. The Start must be reachable
        (distance >= 0) from the End using only open cells.

        From the problem statement: "Among shortest paths, the Snake prefers to go
        up, then right, then down, then left.". The returned paths obey this preference.
        It excludes the start and includes the end. Hence its size is the number of
        steps a snake traveling the path takes.

        @apiNote
            Do not attempt to run this method with a "distanceFromStart, sourceStart,
            reachableEnd" combination then reverse the path. Such does not produce
            anything close to the correct path. Changing neighbor exploration order
            will not help.
     */
    public static ArrayList<Cell> reconstructPath(
        final Grid<Integer> distanceFromEnd,
        final Cell sourceEnd,
        final Cell reachableStart
    ) {
        assert distanceFromEnd.get(sourceEnd) == 0;
        assert distanceFromEnd.get(reachableStart) >= 0;
        assert isConsistent(distanceFromEnd);
        if (sourceEnd.equals(reachableStart)) {
            return new ArrayList<>(0);
        }
        final int length = distanceFromEnd.get(reachableStart);
        final ArrayList<Cell> path = new ArrayList<>(length);
        Cell current = reachableStart;
        for (int step = length; step > 0; step -= 1) {
            for (final Cell neighbor : current.getNeighborsURDL(distanceFromEnd)) {
                final int expected = step - 1;
                if (distanceFromEnd.get(neighbor) == expected) {
                    path.add(neighbor);
                    current = neighbor;
                    break;
                }
            }
        }
        assert current.equals(sourceEnd) && !path.contains(reachableStart);
        return path;
    }

    private static boolean isConsistent(final Grid<Integer> distances) {
        final BiFunction<Cell, Cell, Boolean> alongEdges = (cell, neighbor) ->
            distances.get(cell) <= -1 ||
            distances.get(neighbor) <= -1 ||
            Math.abs(distances.get(cell) - distances.get(neighbor)) <= 1;
        final Predicate<Cell> acrossCells = cell ->
            cell
                .getNeighbors(distances)
                .stream()
                .allMatch(neighbor -> alongEdges.apply(cell, neighbor));
        return distances.stream().map(Pair::second).allMatch(acrossCells);
    }
}
